site_name: MLGym
<!-- site_url: <https://mlgym.com> --> # We don't have site url yet, we will build docs locally and then host.
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    annotation: material/chevron-right-circle
  custom_dir: docs/overrides
  logo: assets/logos/mlgym_logo.png
  favicon: assets/favicon.ico
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - scheme: default
      # primary: black  # override in custom.css
      accent: deep orange
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      # primary: black  # override in custom.css
      accent:
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.indexes
    - navigation.top
    - content.action.edit
    - navigation.footer
    - content.code.copy
    - content.footnote.tooltips
    - header.autohide
    - announce.dismiss
    - content.code.annotate
    - navigation.tabs
    - navigation.tabs.sticky
markdown_extensions:

- admonition
- pymdownx.details
- pymdownx.tabbed:
      alternate_style: true
- pymdownx.superfences
- pymdownx.magiclink
- footnotes
- attr_list
- md_in_html
- pymdownx.snippets:
      check_paths: true
- pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
nav:
- Getting Started:
  - index.md
  # add installation and basic tutorial md files here.
- Architecture:
  - "architecture/index.md"
  # add architecture details here. This section should explain the design of MLGym without diving deep into the API details.
- User Guides:
  - "usage/index.md"
  # Add usage guide for each component of MLGym here. Agents (not specific to the BaseAgent class, but generally how to integrate any agent. hold off on it because we are reworking it), Tools (adding custom tools, using existing tools etc.), Tasks (explain variables of the task, how to add new task), Datasets (how to add new dataset and use it in tasks), Environment (how to interact with the environment API, structure of environment functionality). Configuration options available for the package.
plugins:
- glightbox
- search
- include-markdown
- mike:
      canonical_version: latest
      version_selector: true
- mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [mlgym]
          options:
            merge_init_into_class: true
            summary: false
            show_root_heading: true
            heading_level: 2
            docstring_style: google
            show_if_no_docstring: true
            show_signature: true
            show_signature_annotations: true
            signature_crossrefs: true
            separate_signature: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            extensions:
              - griffe_pydantic:
                  schema: false
            filters:
              - "!^_"
              - "!^model_config"
              - "!^model_post_init"
repo_url: <https://github.com/facebookresearch/MLGym>
repo_name: facebookresearch/MLGym
edit_uri: edit/main/docs/
extra_javascript:
- assets/js/sh-annotation.js
extra_css:
# files are from SWE-Agent codebase, we need to check if we need
- assets/custom.css
- assets/mkdocstrings.css
- assets/image_theme.css
extra:
  version:
    provider: mike
